#include "astTest/primitiveDeclarations.c"
#include "astTest/structDeclarations.c"
#include "astTest/enums.c"
#include "astTest/funcs.c"
#include "astTest/if.c"
#include "astTest/goto.c"
#include "astTest/operations.c"
#include "astTest/switch.c"
