name: C CI

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: valgrind
        version: 1.0

    - uses: actions/checkout@v3
    - name: make
      run: make DEBUG=1 -j
    - name: make test
      run: make build/allTests DEBUG=1 -j
    - name: run tests
      run: build/allTests
    - name: memory leak check
      run: valgrind --error-exitcode=1 --leak-check=full build/ccompiler assets/astTest.c
